application:
  applicationName: "gateway"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        CUSTOMER_API_HOST: "customer.gabbar-dev.svc.cluster.local"
        CUSTOMER_API_PORT: "8080"
        CATALOG_API_HOST: "catalog.gabbar-dev.svc.cluster.local"
        CATALOG_API_PORT: "8080"
        INVENTORY_API_HOST: "inventory.gabbar-dev.svc.cluster.local"
        INVENTORY_API_PORT: "8080"
        DISABLE_CART_DISCOVERY: "false"
        CART_API_HOST: "cart.gabbar-dev.svc.cluster.local"
        CART_API_PORT: "8080"
        PRODUCT_SEARCH_API_HOST: "search.gabbar-dev.svc.cluster.local"
        PRODUCT_SEARCH_API_PORT: "8080"
        REVIEW_API_HOST: "review.gabbar-dev.svc.cluster.local"
        REVIEW_API_PORT: "8080"
        PROMOTION_API_HOST: "promotion.gabbar-dev.svc.cluster.local"  
        PROMOTION_API_PORT: "8080"  
        HTTP_PORT: "8080"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
  deployment:
    imagePullSecrets: nexus-docker-config-forked
    additionalLabels:
      appCategory: "backend"
    annotations:
    volumes: {}
    image:
      repository: stakater/stakater-nordmart-gateway-vertx
      tag: v0.0.1
    envFrom:
    - type: configmap
      name: ""    
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 8080
  service:
    ports:
    - port: 8080
      name: http
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  route:
    enabled: true
 