application:
  applicationName: "gateway"
  deployment:
    imagePullSecrets: nexus-creds
    additionalLabels:
      appCategory: "backend"
    annotations:
    volumes: {}
    image:
      repository: stakater/stakater-nordmart-gateway-vertx
      tag: v0.0.1
    env:
    - name: CUSTOMER_API_HOST
      value: "customer.gabbar-dev.svc.cluster.local"
    - name: CUSTOMER_API_PORT
      value: "8080"
    - name: CATALOG_API_HOST
      value: "catalog.gabbar-dev.svc.cluster.local"
    - name: CATALOG_API_PORT
      value: "8080"
    - name: INVENTORY_API_HOST
      value: "inventory.gabbar-dev.svc.cluster.local"
    - name: INVENTORY_API_PORT
      value: "8080"
    - name: DISABLE_CART_DISCOVERY
      value: "false"
    - name: CART_API_HOST
      value: "cart.gabbar-dev.svc.cluster.local"
    - name: CART_API_PORT
      value: "8080"
    - name: PRODUCT_SEARCH_API_HOST
      value: "search.gabbar-dev.svc.cluster.local"
    - name: PRODUCT_SEARCH_API_PORT
      value: "8080"
    - name: REVIEW_API_HOST
      value: "review.gabbar-dev.svc.cluster.local"
    - name: REVIEW_API_PORT
      value: "8080"
    - name: PROMOTION_API_HOST
      value: "promotion.gabbar-dev.svc.cluster.local"  
    - name: PROMOTION_API_PORT
      value: "8080"       
    - name: HTTP_PORT
      value: "8080"
  
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 8080
  service:
    ports:
    - port: 8080
      name: http
      targetPort: 8080
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  configMap:
   enabled: false
  route:
    enabled: true
 