applicationName: "gateway"
deployment:
  podLabels:
    app: gateway
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 8080
  image:
    repository: stakater/stakater-nordmart-gateway-vertx
    tag: v0.0.1
  env:
  - name: CUSTOMER_API_HOST
    value: "customer"
  - name: CUSTOMER_API_PORT
    value: "8080"
  - name: CATALOG_API_HOST
    value: "catalog"
  - name: CATALOG_API_PORT
    value: "8080"
  - name: INVENTROY_API_HOST
    value: "inventory"
  - name: INVENTROY_API_PORT
    value: "8080"
  - name: DISABLE_CART_DISCOVERY
    value: "false"
  - name: CART_API_HOST
    value: "cart"
  - name: CART_API_PORT
    value: "8080"
  - name: PRODUCT_SEARCH_API_HOST
    value: "search"
  - name: PRODUCT_SEARCH_API_PORT
    value: "8080"
  - name: HTTP_PORT
    value: "8080"
rbac:
  create: true
  serviceAccount:
    create: true
configMap: {}
service:
  ports:
  - port: 8080
    name: https
    targetPort: 8080
  additionalLabels:
    expose: "true"
    annotations:
      config.xposer.stakater.com/Domain: DOMAIN
      config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}'
      config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}-{{.Namespace}}.{{.Domain}}'
      config.xposer.stakater.com/TLS: 'true'
      config.xposer.stakater.com/TLSSecretNameTemplate: "tls-cert"
      xposer.stakater.com/annotations: |-
        kubernetes.io/ingress.class: external-ingress
        forecastle.stakater.com/expose: true
        forecastle.stakater.com/icon: https://github.com/stakater/ForecastleIcons/raw/master/stakater.png
        forecastle.stakater.com/appName: Gateway-NAMESPACE
        forecastle.stakater.com/group: Nordmart
        monitor.stakater.com/enabled: true
        ingress.kubernetes.io/force-ssl-redirect: true
        exposeIngressUrl: locally
