apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.0.1
  name: gateway
  namespace: {NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      imagePullSecrets:
      - name: docker-nexus-registry-secret
      containers:
      - name: gateway
        image: "{IMAGE}"
        env:
        - name: CATALOG_API_HOST
          value: "catalog.coolstore"
        - name: CATALOG_API_PORT
          value: "8080"
        - name: INVENTROY_API_HOST
          value: "inventory.coolstore"
        - name: INVENTROY_API_PORT
          value: "8080"
        - name: DISABLE_CART_DISCOVERY
          value: "false"
        - name: CART_API_HOST
          value: "cart.coolstore"
        - name: CART_API_PORT
          value: "8080"
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080